@startuml product-editor-sequence-diagram

skinparam guillemet false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam style strictuml
skinparam sequenceParticipant underline
hide circle

title Add product process

actor "Staff" as staff
participant "Administration" as admin <<main>>


staff -> admin: runs program
activate admin

create "Main Screen" as main <<JFrame>> 
admin -> main: <<construct>>
deactivate admin
activate main
main --> staff: displays main menu

staff -> main: <<UI event>> clicks Add a New Product

create "AddProducts" as dialog <<JDialog>>
main -> dialog: <<construct>>
deactivate main
create "Db Manage Products" as dbman <<DAO>>
activate dialog
dialog->dbman: <<construct>>
activate dbman
staff <-- dialog: displays dialog frame


dialog -> dbman: getCategories()
database "Database" as dao
dbman->dao: SELECT DISTINCT category FROM product
activate dao
dbman<--dao: Collection<String>
deactivate dao
dialog<--dbman: Collection<String>
deactivate dbman

create "Simple List Model" as slm <<Helper>>
dialog -> slm: <<construct>>
activate slm
dialog-> slm: updateItems(categories)
deactivate slm

dialog -> dialog: txt.categorysetModel(simpleListModel)

staff -> dialog: inputs product details

alt saves product
    staff -> dialog: <<UI event>> clicks save product
    
    dialog -> dialog: getProduct() : id, name, description, category, price, quantity
    create "Product" as product <<Domain>> 
    dialog -> product: <<construct>>
    activate product
    dialog <-- product: instance created
    deactivate product
    dialog -> dbman: saveProduct(instance)
    activate dbman
    dbman ->dao : MERGE INTO product ? VALUES ?
    activate dao
    dbman <-- dao : product merged
    dbman->dbman : construct a product list from data
    deactivate dao
    dialog <-- dbman : Collection<String>
    deactivate dbman
    dialog -> dialog: dispose()
    destroy dialog
else doesnt want to save
    staff -> dialog: <<UI event>> clicks cancel
    dialog -> dialog: dispose()
    destroy dialog
end

@enduml
