@startuml product-viewer-sequence-diagram

skinparam guillemet false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam style strictuml
skinparam sequenceParticipant underline
hide circle

title Delete product process

actor "Staff" as staff
participant "Administration" as admin <<main>>

staff -> admin: runs program
activate admin

create "Main Screen" as main <<JFrame>> 
admin -> main: <<construct>>
deactivate admin
activate main
main --> staff: displays main menu

staff -> main: <<UI event>> clicks view product

create "View Dialog" as dialog <<JDialog>>

main -> dialog: <<construct>>
deactivate main
create "DB Manage Products" as dao <<DAO>>
activate dialog
dialog -> dao: <<construct>>

activate dao
dialog->dao : getProducts()
database "Database" as db
dao -> db: SELECT * FROM product
activate db
dao<--db: data
deactivate db
dao->dao : construct a product list from data

dialog <-- dao: Collection<products>
deactivate dao




create "Simple List Model" as slm <<Helper>>
dialog -> slm: <<construct>>
activate slm
dialog-> slm: updateItems(categories)
deactivate slm
dialog -> dialog: txt.categorysetModel(simpleListModel)

staff <-- dialog: display list of product

staff->dialog : clicks on product to delete
staff->dialog : <<UI event>> clicks delete button

dialog -> dialog : showConfirmDialog()

alt clicks yes
    staff -> dialog : <<UI event>> clicks yes
    dialog -> dao : deleteProduct(product)
    dao -> db : DELETE FROM product WHERE product_id = ?
    dialog-> slm: updateItems(categories)
    activate slm
    deactivate slm
    dialog -> dialog: txt.categorysetModel(simpleListModel)
    
else clicks no
    staff -> dialog : <<UI event>> clicks no
end





staff -> dialog: <<UI event>> clicks close
dialog -> dialog: dispose()
destroy dialog

@enduml
